### ISSUE TITLE
运行后，缺少CSS文件

### ISSUE THREAD

**Issue by aixj1984** [acmenlei/codecv#11]
![微信截图_20230908161134](https://github.com/acmenlei/codecv/assets/2499352/cad737d0-48d3-4ea7-95ce-4c51d0272476)

Unknown variable dynamic import: ../templates/modules/create/style.scss

**Comment by aixj1984** [comment]
好吧，我觉得至少给一个可以跑起来的例子吧

**Comment by acmenlei** [comment]
ok 已补充相关文件 重新拉一下即可

**Comment by aixj1984** [comment]
可以了
