### ISSUE TITLE
多列布局的宽度可以调整吗

### ISSUE THREAD

**Issue by zys1346** [acmenlei/codecv#13]
多列布局可以单独固定一栏的宽度吗

**Comment by acmenlei** [comment]
这个特性目前暂时不支持，在后面的版本中可能会考虑

**Comment by zys1346** [comment]
自定义CSS也无法实现是吗

**Comment by acmenlei** [comment]
有能力写css 当然是可以实现的，你需要精准定位到目标元素列再去指定宽度，否则可能会导致影响其他多列布局。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月14日 10:46 |
| 收件人 | acmenlei/codecv ***@***.***> |
| 抄送人 | coderlei ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [acmenlei/codecv] 多列布局的宽度可以调整吗 (Issue #13) |

自定义CSS也无法实现是吗
