### ISSUE TITLE
能否开源一下服务端导出接口的代码

### ISSUE THREAD

**Issue by jscslld** [acmenlei/codecv#6]

**Comment by acmenlei** [comment]
后端暂时不打算开源，但导出使用了puppeteer，你可以移步这篇文章查看[https://juejin.cn/post/7263035818047373367](https://juejin.cn/post/7263035818047373367)

**Comment by jscslld** [comment]
好的，谢谢大佬。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月5日(周六) 下午3:57
收件人: ***@***.***&gt;;
抄送: "Lu ***@***.******@***.***&gt;;
主题: Re: [acmenlei/codecv] 能否开源一下服务端导出接口的代码 (Issue #6)




 
后端暂时不打算开源，但导出使用了puppeteer，你可以移步这篇文章查看https://juejin.cn/post/7263035818047373367
